#Pod creation with emptyDir
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html
      subPath: html
    ports:
      - containerPort: 80
  volumes:
  - name: nginx-storage
    emptyDir: {}
---
#Lets create another with hostpath volume
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html
    ports:
      - containerPort: 80    #Port of the Container exposed for nginx application
  volumes:
  - name: nginx-storage
    hostPath:
      path: /data
      type: Directory #DirectoryOrCreate, FileOrCreate, File, Socket, CharDevice, BlockDevice