#Covert the password which you want to set to root user using base64
#echo -n "test123" | base64
#take the output and update the secret file
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret
data:
  mysql_root_passwd: Mzk1MjgkdmRnN0pi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysqldb-secret
              key: mysql_root_passwd
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /mysql_data
          type: DirectoryOrCreate
#Now check the mysql connection with help of creating temporary container to
#check the mysql access
#kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mysql -pXXXXX